export const GET_CANDIDATE_RESULTS_REQUEST = "GET_CANDIDATE_RESULTS_REQUEST";
export const GET_CANDIDATE_RESULTS_SUCCESS = "GET_CANDIDATE_RESULTS_SUCCESS";
export const GET_CANDIDATE_RESULTS_FAILURE = "GET_CANDIDATE_RESULTS_FAILURE";
